### ISSUE TITLE
info button does not change into cross button when I click on it

### ISSUE THREAD

**Issue by biancalina** [codetapacademy/my-cv-v2-junior#13]
Good morning! I am trying to create this pink buttons 
![image](https://user-images.githubusercontent.com/57066370/72606510-a34cbb00-3916-11ea-9a96-e12e60fc9c07.png). When I click on the `info-button` it should open the content and change into `cross-button`. The content opens when I click on it, but the info button doesn't change. 
![image](https://user-images.githubusercontent.com/57066370/72606854-53babf00-3917-11ea-8e9c-f563f3af6c88.png)
How can I do it? Thank you!

**Comment by marianzburlea** [comment]
I believe you want to have a look at https://github.com/codetapacademy/my-cv-v2-junior/blob/2d154a7f803310500075d1665b09f1e1e72a546b/src/_component/open-source/open-source.scss#L258
Also, open a chat with @BogdanNegura on this matter and start a pair programming session.
If both of you can't figure it out, let me know.

**Comment by biancalina** [comment]
I will speak with Bogdan about this. Thank you!
