### ISSUE TITLE
menu section input reset - label

### ISSUE THREAD

**Issue by BogdanNegura** [codetapacademy/my-cv-v2-junior#21]
As you can see on the image below I'm trying to create and reset input for the initial state and link it with the label ".default-reset". So this input share the same name with the other inputs and the label of this input have the "for" attribute witch share the same name with the "id" of the reset input but are not linked each other. I'll appreciate any suggestion.

![image](https://user-images.githubusercontent.com/44984647/73125005-e7386380-3f99-11ea-93eb-b844deef6bcf.png)

https://youtu.be/p8vgqQJz3xk

**Comment by marianzburlea** [comment]
Hey @BogdanNegura , did you use that `id` anywhere else?

**Comment by biancalina** [comment]
you should have an id for each section. Check my code

**Comment by BogdanNegura** [comment]
yeah, the id was present into other grouped inputs, I should check this first time. Thank you

**Comment by marianzburlea** [comment]
@BogdanNegura , do you still need help with this?
If not, please close it.
