### ISSUE TITLE
modal doesn't work for each section

### ISSUE THREAD

**Issue by biancalina** [codetapacademy/my-cv-v2-junior#24]
Hello, everybody! I am working on the modal section, but it works just for the first section. I followed a video about how to create a modal with HTML, CSS and JS and I adapted the content for my project. This is what I get 
![image](https://user-images.githubusercontent.com/57066370/73448110-119e6e00-4358-11ea-94f2-58fae481fede.png)  but it works just for the first section. What can I do to make it work for each section? Thank you!

**Comment by marianzburlea** [comment]
You're in the same boat as @BogdanNegura 
I've already discussed this with him last night. See if both of you can come up with something, otherwise, I'll help you out
