### ISSUE TITLE
how to rotate arrow-up?

### ISSUE THREAD

**Issue by biancalina** [codetapacademy/my-cv-v2-junior#9]
Good morning, everyone! I got a problem. I'm trying to rotate arrow-up when I click on it, but it doesn't work. I'm trying to create something like this: 
![image](https://user-images.githubusercontent.com/57066370/72050209-7f56fd00-32b8-11ea-8973-fc8e0b6a94ac.png) . This is my code in pug 
![image](https://user-images.githubusercontent.com/57066370/72050403-f2607380-32b8-11ea-8fcc-6e03168382b8.png) . I would like to understand what I am doing wrong. Thank you!

**Comment by marianzburlea** [comment]
You're missing the description!

**Comment by marianzburlea** [comment]
![image](https://user-images.githubusercontent.com/1318985/72049790-921d0200-32b7-11ea-9784-94ac5f48415d.png)
